export enum Gun {
    GUN_KNIFE = 0,
    GUN_PISTOL,
    GUN_CARBINE,
    GUN_SHOTGUN,
    GUN_SUBGUN,
    GUN_SNIPER,
    GUN_ASSAULT,
    GUN_CPISTOL,
    GUN_GRENADE,
    GUN_AKIMBO,
    NUMGUNS
}
